### ISSUE TITLE
Program couldn't run

### ISSUE THREAD

**Issue by nghiabros** [abysshint/tor-control-panel#10]
Hi, I try using the newest version (v2.3.12.20) and the oldest version (v2.2.14.2) on the github release. But these version of program have same issues. How do I fix it?
My windows 10 (64 bit version) is up-to-date. Program folder is moved to the desktop.

![image](https://github.com/abysshint/tor-control-panel/assets/43260081/f0c206a6-cb01-4dcc-b12e-09a38ea31753)

**Comment by abysshint** [comment]
Possible scenarios for the problem are listed in the warning. It is most likely that the tor.exe **file is damaged**.
Checksums of the file **./tor/tor.exe from version 2.3.12.20**:
TCP-win32:
CRC32: B89EC6CF | MD5: D8A7BD4AFB1B95E39E5FAE23D18EBB3C | SHA-1: C2B86BEB1CC7A4BADDB103AC3630B34017473F23

TCP-win64:
CRC32: 2DCDC3EC | MD5: A5599EE9313152017F5E955C30902914 | SHA-1: 90117A27B6F5C17A4C7F88970E0C03C571E0CB28

You can find out the checksum through the [Hashtab program or other alternatives](https://implbits.com/hashtab)

Possible causes of damage:
 - Intrusion of malware into the process of launching executable files
 - Interference by antivirus programs, including Windows Defender
 - Malfunctioning hard drive/RAM

If the checksums match and nothing is corrupted, try:
 - Run the file **./tor/tor.exe** as a normal program and make sure that the tor console window launches without errors.
 - Delete the **TOR.EXE-*.pf** files from the **C:\Windows\Prefetch** folder and restart the Explorer process or computer
 - Remove (if any) third-party tor.exe process launch policies in the Windows registry:
 - Move the program folder to another directory/drive
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\tor.exe`

The program works 100% on Windows 10 x64, the problem is purely local.

**Comment by nghiabros** [comment]
I have found solution: **Turn on UAC on my windows 10**.
Thanks for supporting!
