### ISSUE TITLE
Control remote TOR gateway

### ISSUE THREAD

**Issue by SKJoy** [abysshint/tor-control-panel#11]
I deployed a TOR gateway using Docker on a different Linux box within my LAN and it has the control port open & enabled.

Is it possible to use this utility to connect & control that TOR gateway instance?

- My PC IP where TCP is installed = `192.168.0.XXX`
- IP of the TOR gateway  in LAN = `192.168.0.YYY`
- TOR gateway control port = `ZZZ`

Thanks in advance.

**Comment by abysshint** [comment]
If short, it’s impossible.

At the moment, the program only works with the local tor process, which is launched through the Tor Control Panel. Full control and synchronization of all necessary data only through the control port is an impossible task, because the control port simply does not provide such capabilities.

**Comment by SKJoy** [comment]
**Understood** and **thanks** again for **explaining** it.
