### ISSUE TITLE
Spam notifications

### ISSUE THREAD

**Issue by jestxfot** [abysshint/tor-control-panel#14]
Why does the program change ip addresses so often and is there any way to turn this feature off?

![image](https://github.com/abysshint/tor-control-panel/assets/87380272/b7db276f-2b86-47cf-8c07-da22e50c99ca)

**Comment by abysshint** [comment]
Because it's tor. For the purpose of “anonymity”, every 10 minutes tor itself changes the Exit Circuit, and along with it the IP address changes. The chain also changes if the destination address is not accessible through the current circuit.

1. To increase the chain change interval, go to “Settings -> General” and change the option: “Change a circuit that exists for than N seconds.”

2. It is impossible to prevent circuits from changing, this is the whole point of tor, but to prevent the Exit IP address from changing you can:
    - Switch country filter mode to "Favorite nodes" (Settings -> Filter)
    - In the "Routers" section, manually select only one Exit node. To do this, click on the penultimate column. After this, only nodes marked with the ★ symbol will participate in the construction of circuits.
    - Don't forget to click the "Apply" button and remember that if only one exit node is selected and it stops working, then you will no longer be able to connect to tor.
  
3. If you need the IP address to “not change”, only for certain sites, go to “Settings -> Lists”, enable the option: “Save Exit node for specified hosts”, enter the addresses of sites/domains and set a large interval in seconds.

4. If you're just tired of pop-up notifications about IP address changes, go to "Settings - General" and turn off the "Show pop-up messages" option.

**The same thing in Russian:**

Потому что - это tor. В целях "анонимности", каждые 10 минут tor сам меняет выходную цепочку, а вместе с ней меняется и IP-адрес. Так же цепочка меняется, если адрес назначения недоступен через текущую цепочку.

1. Чтобы увеличить интервал смены цепочки, зайдите в "Настройки -> Общие" и измените опцию: "Менять цепочку существующую более чем N-секунд".

2. Предотвратить изменение цепочек невозможно, в этом весь смысл tor, но чтобы выходной IP-адрес не менялся вы можете:
    - Переключить режим фильтра стран в "Избранные узлы" (Настройки -> Фильтр)
    - В разделе "Роутеры" вручную выбрать только один выходной узел. Для этого щёлкните мышкой по предпоследнему столбцу. После этого, только узлы, помеченные символом ★ будут участвовать при построении цепочек. 
    - Не забудьте нажать кнопку "Применить" и помните, что если выбран только один выходной узел и он перестанет работать, то вы не сможете больше подключиться к tor.
  
3. Если вам нужно, чтобы IP-адрес "не менялся", только для определённых сайтов, зайдите в "Настройки -> Списки", включите опцию: "Сохранять IP-адрес для указанных адресов", введите адреса сайтов/доменов и задайте большой интервал в секундах.

4. Если вам просто надоели всплывающие уведомления о смене IP-адреса, зайдите в "Настройки - Общие" и выключите опцию "Показывать всплывающие сообщения"

**Comment by jestxfot** [comment]
Thanks for the detailed response! I already tried to customize step 1, but it didn't work for some reason. Step 3 seems to work!
