### ISSUE TITLE
Not compatible with Tor Expert Bundle 0.4.7.14

### ISSUE THREAD

**Issue by sagasm** [abysshint/tor-control-panel#7]

**Comment by abysshint** [comment]
Tell in more detail, what exactly is incompatible?
- If the version detected incorrectly, it is most likely due to the fact that the dates and file sizes are the same. Instead of replacing tor.exe , first delete the old one and copy the new one. When copying with replacement, the dates do not change. This "bug" has already been fixed and all will work properly in the next stable version!

**Comment by sagasm** [comment]
1.  0.4.7.14 has different directory structure.
2.  0.4.7.14  do not use obfs4proxy.exe

**Comment by abysshint** [comment]
1. TCP version 2.2.12.7 uses the directories structure from Tor Browser. Support for the tor-expert-bundle 12+ directory structure of the new format has already been [added ](https://github.com/abysshint/tor-control-panel/commit/62e146a8a0dccd00e065bba5954a7c85127a0fe4) and will be available in the next version. The directory structure is not so important. Just move the **geoip**, **geoip6** and **tor.exe** according to the old structure.

2. This too has already been fixed and will be available in the next version. In the meantime, just **rename** the file **lyrebird.exe** in **obfs4proxy.exe** or go to the TCP Settings - Other - Pluggable transports, and **replace** **obfs4proxy.exe** on **lyrebird.exe**
